### ISSUE TITLE
[FYI] unexpected response after update

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/skill-update#94]
### Objective

was told that update was done,
then got told "I don't understand, ......"
then got a screen message "Thank you"

### Initial Implementation Requirements

image device with one level backwards of the beta software,
when up and running - mouse/click on the notification icon, then mouse/click on "CLEAR"
confirm with a 'yes'
wait for update to complete

### Other Considerations

pertinent timestamp of voice & audio logs
[post-update-not-understand.txt](https://github.com/user-attachments/files/16130979/post-update-not-understand.txt)
'
all log files:
[after.update.tar.gz](https://github.com/user-attachments/files/16130988/after.update.tar.gz)

**Comment by NeonDaniel** [comment]
The "Thank you" transcription I've observed with Whisper STT (default in recent Beta releases) when actual silence is recorded. I think this was just a false activation of the WW.
